version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: z9BIE3A2tNHJJqXY
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  neo4j:
    image: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474" # Port pour l'interface web
      - "7687:7687" # Port pour les connexions Bolt
    volumes:
      - $HOME/neo4j/data:/data # Emplacement pour persister les données de Neo4J
    environment:
      - NEO4J_AUTH=none # Désactiver l'authentification

volumes:
  neo4j-data:
  postgres-data: