version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: z9BIE3A2tNHJJqXY
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  neo4j:
    image: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474" # Port pour l'interface web
      - "7687:7687" # Port pour les connexions Bolt
    volumes:
      - ./neo4j/import:/var/lib/neo4j/import

    environment:
      - NEO4J_AUTH=none # Désactiver l'authentification
      - NEO4J_dbms_directories_import=/var/lib/neo4j/import
      - NEO4J_server_memory_pagecache_size=4G
      - NEO4J_server_memory_heap_max__size=4G
volumes:
  neo4j-data:
  postgres-data: